services:
#    sml_platform.example:
#        class: SML\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    sml_platform.antispam:
        class:  SML\PlatformBundle\Antispam\SMLAntispam
        arguments:
            $mailer: "@mailer"
            $minLength: 50
        calls:
            - [ setLocale, ["%locale%"] ]

    sml_platform.email.application_mailer:
        class:  SML\PlatformBundle\Email\ApplicationMailer
        arguments:
            $mailer: "@mailer"

    sml_platform.doctrine_listener.application_creation:
        class: SML\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@sml_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    sml_platform.validator.antiflood:
        class:  SML\PlatformBundle\Validator\AntifloodValidator
        arguments:  ["@request_stack", "@doctrine.orm.entity_manager"]
        tags:
            - {name: validator.constraint_validator, alias: sml_platform_antiflood}

    sml_platform.twig.antispam_extension:
        class: SML\PlatformBundle\Twig\AntispamExtension
        arguments:
            - "@sml_platform.antispam"
        tags:
            - { name: twig.extension }

    sml_platform.form.ckeditor:
        class: SML\PlatformBundle\Form\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor }

    sml_platform.beta.html_adder:
        class: SML\PlatformBundle\Beta\BetaHTMLAdder

    sml_platform.beta.listener:
        class: SML\PlatformBundle\Beta\BetaListener
        arguments:
            - "@sml_platform.beta.html_adder"
            - "2018-10-31"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }
