<?php

namespace SML\PlatformBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdvert($limit)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->innerJoin('a.advert', 'adv')
            ->addSelect('adv')
            ->setMaxResults($limit)
            ->orderBy('a.date', 'DESC');

        return $qb->getQuery()->getResult();
    }


    // Methode pour faire fonctionner le validator Antiflood
    // NE CORRESPOND PAS au test antiflood (@IP avec commentaire posté - de 15 sec avant)
    public function isFlood($ip, $time) {
        if($time == 15)
        {
            return false;
        }
        else
        {
            return true;
        }
    }
}
